---
- hosts: web
  tasks:
    
  - block: 
    - name: install nodejs
      package:
        name: nodejs
        state: latest

    - name: install npm
      package:
        name: npm
        state: latest
    become: yes

  - name: ensure node dir exists
    file:
      path: /home/automation_user/node
      state: directory 

  - name: copy main.js and set permissions
    template:
      src: templates/main.js.j2
      dest: /home/automation_user/node/main.js
      mode: 0755

  - name: npm install forever
    npm:
      name: forever
      path: /home/automation_user/node
      global: yes
    become: yes

  - name: stop main.js forever
    shell: forever stopall

  - name: run main.js forever
    shell: forever start /home/automation_user/node/main.js
